language: generic
sudo: required

services:
  - docker

before_install:
  - docker build  -t mavparadeza/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true mavparadeza/dockerreact npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  name: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-905113843346"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"